FROM python:3.13-slim

WORKDIR /app

ENV PYTHONPATH=/app/src/app/backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "alembic -c /app/src/app/backend/alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]